In [1]:
import pandas as pd
import numpy as np

In [22]:
df=pd.read_csv("criminal_train.csv")
X=df.drop(columns=['PERID','Criminal'])
y=df['Criminal']
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
df_t=pd.read_csv('criminal_test.csv')
df_t1=df_t.drop(columns='100100')
pre=lm.predict(df_t1)
maxx=np.max(pre)
pre1=pre/maxx
pre2=np.round(pre1)

In [24]:
for i in range(11430):
    if pre2[i]==-0:
        pre2[i]=0

In [25]:
df_t = df_t.rename(columns={'100100': 'PERID'})

In [26]:
dataframe1=df_t
dataframe1['Criminal']=pre2
db=dataframe1.iloc[:,[0,71]]
#pd.read_csv('prediction.csv')

In [27]:
db

          PERID  Criminal
0      66583679       0.0
1      35494679       0.0
2      79424679       0.0
3      11744679       0.0
4      31554679       0.0
5      83164679       0.0
6      58474679       0.0
7      40695779       0.0
8      39315779       0.0
9      58415779       0.0
10     23535779       0.0
11     67275779       0.0
12     93485779       0.0
13     29546779       0.0
14     97556779       0.0
15     37797779       0.0
16     36607779       0.0
17     61727779       0.0
18     20827779       0.0
19     52437779       0.0
20     87267779       0.0
21     33287779       0.0
22     30398779       0.0
23     98598779       0.0
24     41818779       0.0
25     69638779       0.0
26     25748779       0.0
27     75368779       0.0
28     99968779       0.0
29     91578779       0.0
...         ...       ...
11400  43750730       0.0
11401  35360730       0.0
11402  51380730       0.0
11403  50480730       0.0
11404  71901730       0.0
11405  96021730       0.0
11406  71331730       0.0
11407  66541730       0.0
11408  29861730       0.0
11409  95071730       0.0
11410  61281730       0.0
11411  57202730       0.0
11412  45402730       0.0
11413  45022730       0.0
11414  99432730       0.0
11415  26732730       0.0
11416  85832730       0.0
11417  45782730       0.0
11418  26493730       0.0
11419  54693730       0.0
11420  97103730       0.0
11421  99713730       0.0
11422  74543730       0.0
11423  57863730       0.0
11424  97294730       0.0
11425  31894730       0.0
11426  98524730       0.0
11427  80134730       0.0
11428  65323398       0.0
11429  90906563       0.0

[11430 rows x 2 columns]

In [28]:
db.to_csv('test_Predictionsl.csv',index=None)